### ISSUE TITLE
Transform in line 96 (cnb.py)

### ISSUE THREAD

**Issue by mkhullar** [krzjoa/bace#2]
Line with issue:
features_doc_logprob = safe_matmult(X, features_weights.T)

Issue:
The transpose is already handled by safe_matmult of math_utils.py.
Sending a transpose value will result in nothing more than the same matrix since it will take the transpose twice.
A[M x N] is used to take a dot with B[P x N] which will always result in an error.

Proposed Fix:
I think if we remove the transpose while calling the safe_matmult code should work fine.

**Comment by krzjoa** [comment]
You were right about this duplicated transposition. I fixed it. :sunglasses:
