### ISSUE TITLE
When built from pip/github I cant import ComplementNB

### ISSUE THREAD

**Issue by datavistics** [krzjoa/bace#3]
`from bayes.classifiers import ComplementNB
`

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-25-5c93f8407974> in <module>()
> ----> 1 from bayes.classifiers import ComplementNB
> 
> ~\Anaconda3\envs\new_ds\lib\site-packages\bayes\classifiers\__init__.py in <module>()
> ----> 1 from cnb import ComplementNB
>       2 from nnb import NegationNB
>       3 from unb import UniversalSetNB
>       4 from snb import SelectiveNB
>       5 #from lwnb import LocallyWeightedNB
> 
> ModuleNotFoundError: No module named 'cnb'

Not sure why, the files are in the same folder as the __init__.py...

**Comment by krzjoa** [comment]
Can you check it again? It should work now.

**Comment by datavistics** [comment]
I tried installing from git and imported _ComplementNB_ got this:
```
(new_ds) C:\Users\DT-Laptop\projects\NapkinML>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from bayes.classifiers import ComplementNB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\DT-Laptop\Anaconda3\envs\new_ds\lib\site-packages\bayes\__init__.py", line 4, in <module>
    from classifiers import ComplementNB, NegationNB, SelectiveNB, UniversalSetNB
ModuleNotFoundError: No module named 'classifiers'
>>>
```

**Comment by krzjoa** [comment]
Hard to say. I tested it only for Python 2.7 and... it works for me :stuck_out_tongue:

**Comment by datavistics** [comment]
Ah, Im testing it on Python 3.6. No worries. Sklearn is coming out with this in their[ v0.20 release](http://scikit-learn.org/dev/modules/generated/sklearn.naive_bayes.ComplementNB.html).

**Comment by Anasse** [comment]
I have the same issue( wanted to try the selective Naive Bayes ), i am working with python 3.6 . Is there any solution? 

Thank you

**Comment by krzjoa** [comment]
It should work now. **bayes-variants** is deprecated in favor of **bace** package :smiley:
